language: node_js
node_js:
  7
script:
- npm install
- npm run build
install:
  npm install -g firebase-tools
after_success:
- firebase use --token ${FIREBASE_TOKEN} production
- firebase use --add ${PROJECT_ID} production
- firebase deploy --token "${FIREBASE_TOKEN}"