language: node_js
node_js:
  7
script:
- npm install
- npm run build
install:
  npm install -g firebase-tools
# deploy:
#   provider: firebase
#   token:
#     secure: $FIREBASE_TOKEN.
#   project: "aniversarry-86ecd"
after_success:
- firebase use --token ${FIREBASE_TOKEN} production
- firebase use --add aniversarry-86ecd production
- firebase deploy --token "${FIREBASE_TOKEN}"