language: node_js
node_js:
  7
script:
- npm install
- npm run build
install:
  npm install -g firebase-tools
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN.
  project: "aniversarry-86ecd"
# after_success:
# - firebase deploy - project aniversarry-86ecd - token $FIREBASE_TOKEN.